force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>社員情報</description>
    <label>社員情報</label>
    <nameField>
        <displayFormat>Q{YY}{MM}{DD}-{0000}</displayFormat>
        <label>社員番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>社員の連絡先である住所(郵便番号ある）</description>
    <label>住所</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>生年月日</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>メール</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>社員氏名</description>
    <label>氏名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <description>社員の連絡先である電場番号</description>
    <label>電話番号</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserInfoEntryController.cls
public class UserInfoEntryController {
    public Employee employee    {get;set;}
    public String pageMessage   {get;set;}
    public Boolean isEditMode   {get;set;}
        
    public UserInfoEntryController(){
        employee = new Employee();
        system.debug('UserInfoEntryController called');
    }
    
    public UserInfoEntryController(ApexPages.StandardController standard){
        system.debug('standard controller called');
        this.employee = new Employee();
        this.isEditMode = false;
        
        String employeeId = standard.getId();
        system.debug('employeeId =' + employeeId);
        if(employeeId != null || employeeId != ''){
            List<Employee__c> cml = [SELECT Id,Name,Name__c,Mail__c,Address__c,PhoneNumber__c,Birthday__c FROM Employee__c WHERE Id=:employeeId];
            if(cml.size() > 0){
                Employee__c cEmployee = cml.get(0);
                this.employee.eId = cEmployee.Id;
                this.employee.eNo = cEmployee.Name;            
                this.employee.eName.setName(cEmployee.Name__c);
                this.employee.eMail.setMail(cEmployee.Mail__c);
                this.employee.eAddress.setAddress(cEmployee.Address__c);
                this.employee.ePhoneNumber.setPhoneNumber(cEmployee.PhoneNumber__c);
                this.employee.eBirthday.setDate(cEmployee.Birthday__c);
                this.isEditMode = true;                
            }
        }
    }
    
    public void saveUserInfo(){
        if(this.isEditMode == true){
            this.employee.renewal();
        } else {
            this.employee.save();
        }
        
        employee = null;
        employee = new Employee();
        this.pageMessage = '社員情報を登録しました。';
    }
}